NAME = libftprintf.a
LIBFT_DIR = ./libft
LIBFT = $(LIBFT_DIR)/libft.a

CC = cc
CFLAGS = -Wall -Wextra -Werror -I. -I$(LIBFT_DIR)
BONUS_FLAG = .bonus

AR = ar rcs
RM = rm -f


SRCS = ft_printf.c \
       print_args.c \
       print_chars.c \
       print_numbers.c \
       print_hex.c \
       print_ptr.c \
       parser_bonus.c

OBJS = $(SRCS:.c=.o)

all: $(NAME)

$(NAME): $(LIBFT) $(OBJS)
	cp $(LIBFT) $(NAME)
	$(AR) $(NAME) $(OBJS)
	@echo "$(NAME) creado con éxito."

bonus: all

$(LIBFT):
	@$(MAKE) -C $(LIBFT_DIR)

%.o: %.c ft_printf.h
	$(CC) $(CFLAGS) -c $< -o $@


clean:
	$(RM) $(OBJS) $(BONUS_OBJS) $(BONUS_FLAG)
	@$(MAKE) -C $(LIBFT_DIR) clean
	@echo "Objetos eliminados."


fclean: clean
	$(RM) $(NAME) $(BONUS_FLAG)
	@$(MAKE) -C $(LIBFT_DIR) fclean
	@echo "Librerías y binarios eliminados."


re: fclean all

.PHONY: all clean fclean re bonus